# State name to ISO 3166-2:IN state code mapping for geoBoundaries IND ADM1
STATE_NAME_TO_CODE = {
    'Andaman and Nicobar Islands': 'AN',
    'Andhra Pradesh': 'AP',
    'Arunāchal Pradesh': 'AR',
    'Assam': 'AS',
    'Bihār': 'BR',
    'Chandīgarh': 'CH',
    'Chhattīsgarh': 'CG',
    'Delhi': 'DL',
    'Dādra and Nagar Haveli and Damān and Diu': 'DN',
    'Goa': 'GA',
    'Gujarāt': 'GJ',
    'Haryāna': 'HR',
    'Himāchal Pradesh': 'HP',
    'Jammu and Kashmīr': 'JK',
    'Jhārkhand': 'JH',
    'Karnātaka': 'KA',
    'Kerala': 'KL',
    'Ladākh': 'LA',
    'Lakshadweep': 'LD',
    'Madhya Pradesh': 'MP',
    'Mahārāshtra': 'MH',
    'Manipur': 'MN',
    'Meghālaya': 'ML',
    'Mizoram': 'MZ',
    'Nāgāland': 'NL',
    'Odisha': 'OD',
    'Puducherry': 'PY',
    'Punjab': 'PB',
    'Rājasthān': 'RJ',
    'Sikkim': 'SK',
    'Tamil Nādu': 'TN',
    'Telangāna': 'TS',
    'Tripura': 'TR',
    'Uttar Pradesh': 'UP',
    'Uttarākhand': 'UK',
    'West Bengal': 'WB'
}
